---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: lazar010/ruo
          resources:
            limits:
              ephemeral-storage: 5Gi
            requests:
              ephemeral-storage: 2Gi
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: /app/model
          volumeMounts:
            - mountPath: /app/model
              name: modelpd
      volumes:
        - name: modelpd
          nfs:
            server: 10.10.3.80
            path: /var/nfs/public

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001